Repository justimmo/php-sdk, pull requests merged in 2018-11, with the labels that each got.

#105 Update: added residential aggregation data
  src/Justimmo/Model/Project.php
  src/Justimmo/Model/Wrapper/V1/ProjectWrapper.php
Labels: done, on hold

#106 Update: added residential aggregation data to v2
  src/Entity/Realty/Realty.php
  src/Entity/Realty/ResidentialAggregationData.php
  src/Request/RealtyRequest.php
Labels: on hold

#107 Extends the realty request
  src/Request/RealtyRequest.php
Labels: done

#108 Changes the type of the ownershipType from string to OwnershipType
  src/Entity/Realty/OwnershipType.php
  src/Entity/Realty/Realty.php
Labels: done
